name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v4
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: deploy to fly.io
        if: ${{ (github.event_name == 'push') && !contains(github.event.head_commit.message, '#skip') }}
        run: flyctl deploy --remote-only
      - name: Deployment success Success
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ success() && (github.event_name == 'push') && !contains(github.event.head_commit.message, '#skip') }}
        with:
          severity: info
          details: Deployment Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Deployment Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Deployment Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    needs: [simple_deployment_pipeline]
    if: ${{ (github.event_name == 'push') && !contains(github.event.head_commit.message, '#skip') }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1ffbb2e04bd950cffea99066469cb16d69a7887e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
