name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
      - name: npm install
        run: npm install
      - name: lint
        if: ${{ !contains(github.event.head_commit.message, '#tagonly') }}
        run: npm run eslint
      - name: build
        if: ${{ !contains(github.event.head_commit.message, '#tagonly') }}
        run: npm run build
      - name: test
        if: ${{ !contains(github.event.head_commit.message, '#tagonly') }}
        run: npm run test
      - name: e2e tests
        if: ${{ !contains(github.event.head_commit.message, '#tagonly') }}
        uses: cypress-io/github-action@v4
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: deploy to fly.io
        if: ${{ (github.event_name == 'push') && !contains(github.event.head_commit.message, '#skip') && !contains(github.event.head_commit.message, '#tagonly') }}
        run: flyctl deploy --remote-only
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
